# Generated by Django 5.2 on 2025-05-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publisher_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='city',
        ),
        migrations.AddField(
            model_name='author',
            name='birthdate',
            field=models.DateField(default='2002-04-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='rating',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='rating',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
